defaultSemverRangePrefix: ""

enableTelemetry: false

nodeLinker: node-modules

# Yarn will use global content addressable storage to reduce node_modules size across all the projects using this option https://yarnpkg.com/configuration/yarnrc#nmMode
nmMode: "hardlinks-global"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-berry.cjs
